{% set name = "p-winds" %}
{% set version = "0.6.2b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ladsantos/p-winds/archive/refs/tags/v0.6.2-beta.tar.gz
  sha256: cc30a03b4c6d374b554bb137653a52ec8edeba06cc109b5b9e2e4c143549ec74

build:
  noarch: python

  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy
    - scipy
    - astropy
    - flatstar

test:
  imports:
    - p_winds
  commands:
    - pytest
  requires:
    - pytest
  source_files:
    - tests/

about:
  home: https://github.com/ladsantos/p-winds
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python implementation of Parker wind models for exoplanet atmospheres'
  doc_url: https://p-winds.readthedocs.io/
  dev_url: https://ladsantos.org

extra:
  recipe-maintainers:
    - ladsantos
