{% set name = "p-winds" %}
{% set version = "0.5.4b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ladsantos/p-winds/archive/refs/tags/v0.5.4-beta.tar.gz
  sha256: 69fd907a1aea9bd1ad5244c619f012863bbff294caeee6d51484e5760cc8c2cb

build:
  noarch: python

  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy
    - scipy
    - astropy
    - pillow

test:
  imports:
    - p_winds
  commands:
    - pytest
  requires:
    - pytest
  source_files:
    - tests/

about:
  home: https://github.com/ladsantos/p-winds
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python implementation of Parker wind models for exoplanet atmospheres'
  doc_url: https://p-winds.readthedocs.io/
  dev_url: https://ladsantos.org

extra:
  recipe-maintainers:
    - ladsantos
